# Generated by Django 2.1.7 on 2019-04-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_and_registraion', models.CharField(max_length=255)),
                ('induction_programme', models.IntegerField()),
                ('welcome_address', models.CharField(max_length=255)),
                ('induction_lectures', models.CharField(max_length=255)),
                ('induction_of_new_members', models.CharField(max_length=255)),
                ('welcome_address_by_president', models.CharField(max_length=150)),
                ('remarks', models.CharField(max_length=200)),
                ('photograph', models.CharField(max_length=255)),
                ('documentary_on_cpn', models.CharField(max_length=255)),
                ('lunch', models.CharField(max_length=255)),
                ('annual_general_meeting', models.CharField(max_length=255)),
                ('dinner_and_presentation_of_awards_and_certificate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('introduction', models.CharField(blank=True, max_length=100)),
                ('theme', models.TextField(default='Theme of Event', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField(default='')),
                ('location', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='agenda_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='schedule.Event'),
        ),
    ]
